services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: vineyard_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - vineyard_net

  web:
    build: .
    command: >
      bash -c "python manage.py makemigrations vineyard_model &&
               python manage.py migrate &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=vineyard_db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db
    networks:
      - vineyard_net

volumes:
  postgres_data:

networks:
  vineyard_net:
    driver: bridge